# Generated by Django 4.2.3 on 2023-07-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_contas_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='valor',
        ),
    ]
