# Generated by Django 4.2.3 on 2023-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_remove_contas_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='url',
        ),
        migrations.AddField(
            model_name='contas',
            name='valor',
            field=models.CharField(default='', max_length=65),
        ),
    ]
