# Generated by Django 4.2.3 on 2023-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_contas_url_contas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='status',
            field=models.CharField(default='', max_length=65),
        ),
    ]
