# Generated by Django 4.2.3 on 2023-07-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_contas_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='data',
            new_name='vencimento',
        ),
    ]
