# Generated by Django 4.2.3 on 2023-07-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContasCategorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luz',
            new_name='Light',
        ),
        migrations.AlterModelOptions(
            name='light',
            options={'verbose_name': 'Light', 'verbose_name_plural': 'Light'},
        ),
    ]
