# Generated by Django 4.2.3 on 2023-07-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContasCategorias', '0002_rename_luz_light_alter_light_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Light',
            new_name='Luz',
        ),
        migrations.AlterModelOptions(
            name='agua',
            options={'verbose_name': 'Agua', 'verbose_name_plural': 'Agua'},
        ),
        migrations.AlterModelOptions(
            name='luz',
            options={'verbose_name': 'Luz', 'verbose_name_plural': 'Luz'},
        ),
        migrations.AlterModelOptions(
            name='net',
            options={'verbose_name': 'Net', 'verbose_name_plural': 'Net'},
        ),
        migrations.AlterModelOptions(
            name='planodesaude',
            options={'verbose_name': 'PlanoDeSaude', 'verbose_name_plural': 'PlanoDeSaude'},
        ),
    ]
